config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('mirim.urls')),
    path('reservation/', include('reservation.urls')),
    path('gallery/', include('gallery.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

gallery/urls.py
from django.urls import path
from . import views

app_name = 'gallery'

urlpatterns = [
    path('', views.gallery, name='gall_index'),

    path('location/Entrance/', views.Entrance, name='entrance'),
    path('location/BackSide/', views.BackSide, name='backside'),
    path('location/Garden/', views.Garden, name='garden'),
    path('location/Indoor/', views.Indoor, name='indoor'),
    path('location/Roof/', views.Roof, name='roof'),

    path('photographer/profile/', views.profile, name='profile'),
    path('photographer/bada/', views.bada, name='bada'),
    path('photographer/jeongmi/', views.jeongmi, name='jeongmi'),
    path('photographer/seeun/', views.seeun, name='seeun'),
    path('photographer/dayeon/', views.dayeon, name='dayeon'),
    path('photographer/yeyoung/', views.yeyoung, name='yeyoung'),
    path('photographer/seoyeon/', views.seoyeon, name='seoyeon'),
    path('photographer/yeseo/', views.yeseo, name='yeseo'),
    path('photographer/minseo/', views.minseo, name='minseo'),
    path('photographer/sael/', views.sael, name='sael'),
    path('photographer/narae/', views.narae, name='narae'),
    path('photographer/haewon/', views.haewon, name='haewon'),
    path('photographer/seoyoung/', views.seoyoung, name='seoyoung'),
    path('photographer/jinmin/', views.jinmin, name='jinmin'),
    path('photographer/jinhee/', views.jinhee, name='jinhee'),

    path('project/main/', views.project, name="project"),
    path('project/1/', views.project1, name='project1'),
    path('project/2/', views.project2, name='project2'),
    path('project/3/', views.project3, name='project3'),
    path('project/4/', views.project4, name='project4'),
    path('project/5/', views.project5, name='project5'),
    path('project/6/', views.project6, name='project6'),
    path('project/7/', views.project7, name='project7'),
    path('project/8/', views.project8, name='project8'),
    path('project/9/', views.project9, name='project9'),



]

mirim/urls.py
from django.urls import path, include
from . import views

app_name = 'mirim'

urlpatterns = [
    path('', views.index, name='index'),

]

reservation/urls.py
from django.urls import path
from . import views

app_name = 'reservation'

urlpatterns = [
    path('', views.reservationList, name='list'),
    path('individual/', views.individual, name='individual'),
    path('group/', views.group, name='group'),
    path('my_page/', views.myPage, name='my_page'),
    path('review/', views.review, name="review"),

    path('insertReview/', views.insertReview, name='insertReview'),
    path('delReservation/<int:date>', views.delReservation, name='delReservation'),
    path('insertI/', views.insertIndivid, name='insertIndivid'),
    path('insertG/', views.insertGroup, name='insertGroup'),

]

reservation/models.py
from django.db import models

class Reservation(models.Model):
    grade = models.CharField(null=False, default="No Grade", max_length=10, verbose_name="학번")
    name = models.CharField(null=False, default="No Name", max_length=10, verbose_name="이름")
    email = models.CharField(null=False, default="No mail", max_length=25, verbose_name="이메일")
    phone = models.CharField(null=False, default="No Number", max_length=15, verbose_name="연락처")
    person = models.IntegerField(null=False, default=0, verbose_name="인원")
    photographer = models.CharField(null=False, default="Not Chose", max_length=10, verbose_name="작가")
    date = models.IntegerField(null=False, default=0)
    date_str = models.CharField(null=False, default="No date", max_length=30)
    check = models.CharField(null=False, default="확정 대기", max_length=10, verbose_name="촬영 여부")
    review_check = models.BooleanField(default=False)


class Review(models.Model):
    name = models.CharField(null=False, default="No Name", max_length=10)
    grade = models.CharField(null=False, default="No Grade", max_length=20)
    title = models.CharField(null=False, default="No email", max_length=25)
    content = models.CharField(null=False, default="No content", max_length = 200)
    date_str = models.CharField(null=False, default="No date", max_length=30)

reservation/views.py
import allauth.account.utils
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from reservation.models import Reservation, Review
import datetime
from django.contrib.auth import get_user_model
import json

#예약 현황
def reservationList(request):
    if(request.GET.get('photographer')):
        name = request.GET.get('photographer')
        photographer = Reservation.objects.filter(photographer=name)

        p_list = []

        for p in photographer:
            year = str(p.date)[0:4]
            month = str(p.date)[4:6]
            day = str(p.date)[6:8]
            date = year+"/"+month+"/"+day
            p_list.append(date)

        return render(request, 'reservation/Calendar.html', {'p_list' : p_list})
    else:
        return render(request, 'reservation/Calendar.html')

#예약
def individual(request):
    return render(request, 'reservation/reservation_individual.html')

#그룹예약
def group(request):
    return render(request, 'reservation/reservation_group.html')

#내 예약 현황
def myPage(request):
    User = request.user
    reservations = Reservation.objects.filter(name=User.first_name).order_by('-date')
    return render(request, 'reservation/my_reservation.html', {'indiv': reservations})

#리뷰달러가기
def review(request):
    User = request.user
    reservations = Reservation.objects.filter(name=User.first_name, review_check=False, check="촬영 완료").order_by('-date')
    return render(request, 'reservation/reservation_review.html', {'reservations': reservations})

#리뷰값 DB에 Insert
def insertReview(request):
    User = request.user
    username = User.first_name
    grade = User.last_name
    date = request.POST['date'];
    title = request.POST['title'];
    content = request.POST['content'];


    
    #DB에 리뷰 넣는 코드 작성
    newreview = Review(name=username, grade=grade, date_str=date, title=title, content=content)
    newreview.save()
    #review_check true로 바꾸기
    t_reservation = Reservation.objects.filter(name=username, date_str=date)
    t_reservation.update(review_check=True)


    return HttpResponseRedirect('/reservation/my_page')


#예약 취소
def delReservation(request, date):
    User = request.user
    Reservation.objects.filter(name=User.first_name, date=date).delete();
    reservations = Reservation.objects.filter(name=User.first_name).order_by('date_str')
    return render(request, 'reservation/my_reservation.html', {'indiv': reservations})

#개인 예약 DB에 넣는 함수
def insertIndivid(request):
    grade = request.POST['grade']
    name = request.POST['name']
    email = request.POST['email']
    phone = request.POST['phone']
    photographer = request.POST['photo_g']
    date = int(request.POST['date'])
    date_string = request.POST['date']
    date_str = date_string[0:4]+"년 "+date_string[4:6]+"월 "+date_string[6:8]+"일"



    qs = Reservation(grade=grade, name=name, email=email, phone=phone, person=1, photographer=photographer, date=date, date_str=date_str)
    qs.save()
    return HttpResponseRedirect(reverse('reservation:my_page'))

#그룹 예약 DB에 넣는 함수
def insertGroup(request):
    grade = request.POST['grade']
    name = request.POST['name']
    email = request.POST['email']
    phone = request.POST['phone']
    person = request.POST['person']
    photographer = request.POST['photo_g']
    date = int(request.POST['date'])
    date_string = request.POST['date']
    date_str = date_string[0:4] + "년 " + date_string[4:6] + "월 " + date_string[6:8] + "일"

    qs = Reservation(grade=grade, name=name, email=email, phone=phone, person=person, photographer=photographer, date=date, date_str=date_str)
    qs.save()

    return HttpResponseRedirect(reverse('reservation:my_page'))

reservation/templates/reservation/my_reservation.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Mirim in Photo | 내 예약</title>
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/review.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/myreservation.css' %}" type="text/css">
    </head>

    <body>
        <a href="{% url 'mirim:index' %}">
            <img class="logo" src="{% static 'img/logo.svg' %}" />
        </a>
        <main>
            <nav>
                <a href="{% url 'reservation:list' %}"><div class="nav-btn" id="btn-status">예약 현황</div></a>
                <a href="{% url 'reservation:individual' %}"><div class="nav-btn" id="btn-individual">개인 예약</div></a>
                <a href="{% url 'reservation:group' %}"><div class="nav-btn" id="btn-group">단체 예약</div></a>
                <a href="{% url 'reservation:my_page' %}"><div class="nav-btn" id="btn-myrev">내 예약</div></a>
                <a href="{% url 'account_logout' %}"><div class="logout-btn">로그아웃 ></div></a>
            </nav>
            <section>
                <div class="inner-nav">
                    <div class="inner-nav-btn">RESERVATION</div>
                    <a href="{% url 'gallery:entrance' %}"><div class="inner-nav-btn">GALLERY</div></a>
                </div>
                <!-- <div class="scroll-animate"><span></span></div> -->
                <div class="rev-container">
                    {% for i in indiv %}
                        {% if i.check == "확정 대기" %}
                            <div class="waiting-rev">
                                <div class="rev-content">
                                    <div class="division-rev">
                                        {% if i.person > 1%}
                                            단체
                                        {% else %}
                                            개인
                                        {% endif %}
                                    </div>
                                    <div class="date-rev">{{ i.date_str}}</div>
                                    <div class="status-rev">확정 대기 중</div>
                                    <div class="editor-rev-container">작가<div class="editor-rev">{{i.photographer}}</div></div>
                                    <a href="{% url 'reservation:delReservation' date=i.date %}"><div class="cancel-btn">예약 취소</div></a>
                                </div>
                            </div>
                        {% elif i.check == "예약 확정" %}
                            <div class="confirm-rev">
                                <div class="rev-content">
                                    <div class="division-rev">
                                        {% if i.person > 1%}
                                            단체
                                        {% else %}
                                            개인
                                        {% endif %}
                                    </div>
                                    <div class="date-rev">{{ i.date_str}}</div>
                                    <div class="status-rev">예약 확정</div>
                                    <div class="editor-rev-container">작가<div class="editor-rev">{{i.photographer}}</div></div>
                                </div>
                            </div>
                        {% else %}
                            <div class="complete-rev">
                                <div class="rev-content">
                                    <div class="division-rev">
                                        {% if i.person > 1%}
                                            단체
                                        {% else %}
                                            개인
                                        {% endif %}
                                    </div>
                                     <div class="date-rev">{{ i.date_str}}</div>
                                    <div class="status-rev">촬영 완료</div>
                                    <div class="editor-rev-container">작가<div class="editor-rev">{{i.photographer}}</div></div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <a href="{% url 'reservation:review' %}"><img class="review-btn" src="{% static 'img/review_btn.png' %}" /></a>
            </section>
        </main>
    </body>
</html>
{% load static %}

reservation/templates/reservation/reservation_group.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <title>Mirim in Photo | 단체 예약</title>
    <meta charset="UTF-8"/>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/reservation_.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/reservation_group.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/calendar_reservation.css' %}" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>

<body>
    <a href="{% url 'mirim:index' %}">
        <img class="logo" src="{% static 'img/logo.svg' %}" />
    </a>
<main>
    <nav>
        <a href="{% url 'reservation:list' %}"><div class="nav-btn" id="btn-status">예약 현황</div></a>
        <a href="{% url 'reservation:individual' %}"><div class="nav-btn" id="btn-individual">개인 예약</div></a>
        <a href="{% url 'reservation:group' %}"><div class="nav-btn" id="btn-group">단체 예약</div></a>
        <a href="{% url 'reservation:my_page' %}"><div class="nav-btn" id="btn-myrev">내 예약</div></a>
        <a href="{% url 'account_logout' %}"><div class="logout-btn">로그아웃 ></div></a>
    </nav>
    <section>
        <div class="inner-nav">
            <div class="inner-nav-btn reservation">RESERVATION</div>
            <a href="{% url 'gallery:entrance' %}"><div class="inner-nav-btn">GALLERY</div></a>
        </div>
        <div  class = "has-scroll-smooth">
            <div class = "body">
                <!--  style="overflow:auto; width:1280px; height:850px;" -->
                <div class = "main">
                    <div class="text-container">
                        <h3 class = "Explanation">단체 예약 신청서</h3>
                        <h4 class = "Explanation2">1. 점심시간을 이용하여 원하는 공간에서 원하는 소품과 함께 촬영이 진행됩니다.<br>
                            2. 촬영이 끝난 후 'About ME'에 따라 보정이 진행됩니다.<br>
                            3. 지친 하루 끝에 미림의 추억이 담긴 사진이 메일로 전송됩니다.</h4>
                    </div>

                    <form action="{% url 'reservation:insertGroup' %}" method="post">
                        {% csrf_token %}
                        <div class="form-container">
                            <div class="container container1">
                                <div class="item">
                                    <h4>대표자 학번</h4>
                                </div>
                                <input name="grade" class = "grade" type="text" size="30" placeholder="학번을 입력해주세요" style="font-size: 15px;" maxlength="50">
                                <!--add-->
                                <div class = "item item2">
                                    <h4>대표자 이름</h4>
                                </div>
                                <input name="name" class = "name1" type="text" size="30" placeholder="성함을 입력해주세요" style="font-size: 15px;" maxlength="50">
                            </div>

                            <!--add-->
                            <div class = "container">
                                <div class = "item">
                                    <h4>대표자 이메일</h4>
                                </div>
                                <input name="email" type="text" size="30" placeholder="이메일을 입력해주세요" style="font-size: 15px;" maxlength="50">
                            </div>

                            <div class = "container container2">
                                <div class = "item">
                                    <h4>대표자 연락처</h4>
                                </div>
                                <input name="phone" class = "contact" type="text" size="30" placeholder="전화번호를 입력해주세요." style="font-size: 15px;" maxlength="50">

                                <div class = "item">
                                    <h4>참여 인원</h4>
                                </div>
                                <input name="person" class = "INWON" type="number" size="30" placeholder="0" style="font-size: 15px;" maxlength="50">

                            </div>

                            <div class="container container3">
                                <div class="item" style="color: white;">
                                    <h4>작가 선택</h4>
                                </div>
                                <select class = "pg-dropdown" name="photo_g">
                                    <option value="전해원">&nbsp; 전해원</option>
                                    <option value="성진민">&nbsp; 성진민</option>
                                    <option value="한나래">&nbsp; 한나래</option>
                                    <option value="최민서">&nbsp; 최민서</option>
                                    <option value="이예서">&nbsp; 이예서</option>
                                    <option value="이서연">&nbsp; 이서연</option>
                                    <option value="안세은">&nbsp; 안세은</option>
                                    <option value="김바다">&nbsp; 김바다</option>
                                    <option value="김정미">&nbsp; 김정미</option>
                                    <option value="하사엘">&nbsp; 하사엘</option>
                                    <option value="유예영">&nbsp; 유예영</option>
                                    <option value="주진희">&nbsp; 주진희</option>
                                    <option value="양다연">&nbsp; 양다연</option>
                                    <option value="박유진">&nbsp; 박유진</option>
                                    <option value="장서영">&nbsp; 장서영</option>
                                </select>
                            </div>

                            <div class="container container4"><br>
                                <div class="item">
                                    <h4>날짜 선택</h4>
                                </div>
                                <div class="calender">
                                    <div class="header">
                                        <div class="nav">
                                            <h1 id="click_date" style="display: none;"></h1>
                                            <button class="nav-btn-c go-prev" type="button" onclick="prevMonth()">
                                                <img src="{% static 'img/icon_arrows_left.png' %}" width="10px" height="24px"></img>
                                            </button>
                                            <div class="year-month"></div>
                                            <button class="nav-btn-c go-next" type="button" onclick="nextMonth()">
                                                <img src="{% static 'img/icon_arrows_right.png' %}" width="10px" height="24px"></img>
                                            </button>
                                        </div>
                                        <h2 style="color:black; font-size: 25px; margin-top: 5px;"></h2>
                                        <div class="main">
                                            <div class="days"></div>
                                            <div class="dates">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <input type="text" name="date" id="select_date" value="" />

                            <div class="text-container">
                                <h4 class = "thank">
                                    참여해주셔서 감사합니다!<br>
                                    촬영 컨셉에 대한 논의는 메일 또는 카카오톡을 통해 진행됩니다.<br>
                                    촬영 중 교칙 위반으로 인한 불상사에 대해서는 도움을 드릴 수 없습니다.<br>
                                    주의사항을 숙지하신 후 신청해 주시기 바랍니다.
                                </h4>
                            </div>

                            <div class="result-container">
                                <input class="result" type="submit" value="신청하기" onclick="alert('제출되었습니다.')">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</main>
<script src="{% static 'js/calendar_reservation.js'%}" defer></script>
</body>
</html>
{% load static %}

reservation/templates/reservation/reservation_individual.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <title>Mirim in Photo | 개인 예약</title>
    <meta charset="UTF-8"/>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/reservation_.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/reservation_individual.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/calendar_reservation.css' %}" type="text/css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>

<body>
    <a href="{% url 'mirim:index' %}">
        <img class="logo" src="{% static 'img/logo.svg' %}" />
    </a>
<main>
    <nav>
        <a href="{% url 'reservation:list' %}"><div class="nav-btn" id="btn-status">예약 현황</div></a>
        <a href="{% url 'reservation:individual' %}"><div class="nav-btn" id="btn-individual">개인 예약</div></a>
        <a href="{% url 'reservation:group' %}"><div class="nav-btn" id="btn-group">단체 예약</div></a>
        <a href="{% url 'reservation:my_page' %}"><div class="nav-btn" id="btn-myrev">내 예약</div></a>
        <a href="{% url 'account_logout' %}"><div class="logout-btn">로그아웃 ></div></a>
    </nav>
    <section>
        <div class="inner-nav">
            <div class="inner-nav-btn">RESERVATION</div>
            <a href="{% url 'gallery:entrance' %}"><div class="inner-nav-btn">GALLERY</div></a>
        </div>
        <div  class = "has-scroll-smooth">
            <div class="body">
                <div class="main">
                    <div class="text-container">
                        <h3 class="Explanation">개인 예약 신청서</h3>
                        <h4 class="Explanation2">1. 점심시간을 이용하여 원하는 공간에서 원하는 소품과 함께 촬영이 진행됩니다.<br>
                            2. 촬영이 끝난 후 'About ME'에 따라 보정이 진행됩니다.<br>
                            3. 지친 하루 끝에 미림의 추억이 담긴 사진이 메일로 전송됩니다.</h4>
                    </div>
                    <form action="{% url 'reservation:insertIndivid' %}" method="post">
                    {% csrf_token %}
                        <div class="form-container">
                        <div class="container container1">
                            <div class="item item1">
                                <h4>학번</h4>
                            </div>
                            <input class="grade" type="text" size="30" placeholder="학번을 입력해주세요." maxlength="50" name="grade">
                            <div class="item item2">
                                <h4>이름</h4>
                            </div>
                            <input class="name1" type="text" size="30" placeholder="성함을 입력해주세요." maxlength="50"name="name">
                        </div>

                        <div class="container container5">
                            <div class="item">
                                <h4>이메일</h4>
                            </div>
                            <input type="text" size="40" placeholder="이메일을 입력해주세요." maxlength="50" name="email">
                        </div>

                        <div class="container container2">
                            <div class="item">
                                <h4>연락처</h4>
                            </div>
                            <input type="text" size="40" placeholder="연락처를 입력해주세요." maxlength="50" name="phone">
                        </div>

                        <div class="container container3">
                            <div class="item" style="color: white;">
                                <h4>작가 선택</h4>
                            </div>
                            <select class = "pg-dropdown" name="photo_g">
                                <option value="전해원">&nbsp; 전해원</option>
                                <option value="성진민">&nbsp; 성진민</option>
                                <option value="한나래">&nbsp; 한나래</option>
                                <option value="최민서">&nbsp; 최민서</option>
                                <option value="이예서">&nbsp; 이예서</option>
                                <option value="이서연">&nbsp; 이서연</option>
                                <option value="안세은">&nbsp; 안세은</option>
                                <option value="김바다">&nbsp; 김바다</option>
                                <option value="김정미">&nbsp; 김정미</option>
                                <option value="하사엘">&nbsp; 하사엘</option>
                                <option value="유예영">&nbsp; 유예영</option>
                                <option value="주진희">&nbsp; 주진희</option>
                                <option value="양다연">&nbsp; 양다연</option>
                                <option value="박유진">&nbsp; 박유진</option>
                                <option value="장서영">&nbsp; 장서영</option>
                            </select>
                        </div>

                        <div class="container container4"><br>
                            <div class="item">
                                <h4>날짜 선택</h4>
                            </div>
                            <div class="calender">
                                <div class="header">
                                    <div class="nav">
                                        <h1 id="click_date" style="display: none;"></h1>
                                        <button class="nav-btn-c go-prev" type="button" onclick="prevMonth()">
                                            <img src="{% static 'img/icon_arrows_left.png' %}" width="10px" height="24px"></img>
                                        </button>
                                        <div class="year-month"></div>
                                        <button class="nav-btn-c go-next" type="button" onclick="nextMonth()">
                                            <img src="{% static 'img/icon_arrows_right.png' %}" width="10px" height="24px"></img>
                                        </button>
                                    </div>
                                    <h2 style="color:black; font-size: 25px; margin-top: 5px;"></h2>
                                    <div class="main">
                                        <div class="days"></div>
                                        <div class="dates">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <input type="text" name="date" id="select_date" value="" />

                        <div class="text-container">
                            <h4 class="thank">참여해주셔서 감사합니다!<br>
                                촬영 컨셉에 대한 논의는 메일 또는 카카오톡을 통해 진행됩니다.<br>
                                촬영 중 교칙 위반으로 인한 불상사에 대해서는 도움을 드릴 수 없습니다.<br>
                                주의사항을 숙지하신 후 신청해 주시기 바랍니다.
                            </h4>
                        </div>
                        <div class="result-container">
                            <input class="result" type="submit" value="신청하기" onclick="alert('신청되었습니다.')">
                        </div>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
</main>
<script src="{% static 'js/calendar_reservation.js'%}" defer></script>
</body>
</html>
{% load static %}