config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('mirim.urls')),
    path('reservation/', include('reservation.urls')),
    path('gallery/', include('gallery.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

gallery/urls.py
from django.urls import path
from . import views

app_name = 'gallery'

urlpatterns = [
    path('', views.gallery, name='gall_index'),

    path('location/Entrance/', views.Entrance, name='entrance'),
    path('location/BackSide/', views.BackSide, name='backside'),
    path('location/Garden/', views.Garden, name='garden'),
    path('location/Indoor/', views.Indoor, name='indoor'),
    path('location/Roof/', views.Roof, name='roof'),

    path('photographer/profile/', views.profile, name='profile'),
    path('photographer/bada/', views.bada, name='bada'),
    path('photographer/jeongmi/', views.jeongmi, name='jeongmi'),
    path('photographer/seeun/', views.seeun, name='seeun'),
    path('photographer/dayeon/', views.dayeon, name='dayeon'),
    path('photographer/yeyoung/', views.yeyoung, name='yeyoung'),
    path('photographer/seoyeon/', views.seoyeon, name='seoyeon'),
    path('photographer/yeseo/', views.yeseo, name='yeseo'),
    path('photographer/minseo/', views.minseo, name='minseo'),
    path('photographer/sael/', views.sael, name='sael'),
    path('photographer/narae/', views.narae, name='narae'),
    path('photographer/haewon/', views.haewon, name='haewon'),
    path('photographer/seoyoung/', views.seoyoung, name='seoyoung'),
    path('photographer/jinmin/', views.jinmin, name='jinmin'),
    path('photographer/jinhee/', views.jinhee, name='jinhee'),

    path('project/main/', views.project, name="project"),
    path('project/1/', views.project1, name='project1'),
    path('project/2/', views.project2, name='project2'),
    path('project/3/', views.project3, name='project3'),
    path('project/4/', views.project4, name='project4'),
    path('project/5/', views.project5, name='project5'),
    path('project/6/', views.project6, name='project6'),
    path('project/7/', views.project7, name='project7'),
    path('project/8/', views.project8, name='project8'),
    path('project/9/', views.project9, name='project9'),



]

mirim/urls.py
from django.urls import path, include
from . import views

app_name = 'mirim'

urlpatterns = [
    path('', views.index, name='index'),

]

reservation/urls.py
from django.urls import path
from . import views

app_name = 'reservation'

urlpatterns = [
    path('', views.reservationList, name='list'),
    path('individual/', views.individual, name='individual'),
    path('group/', views.group, name='group'),
    path('my_page/', views.myPage, name='my_page'),
    path('review/', views.review, name="review"),

    path('insertReview/', views.insertReview, name='insertReview'),
    path('delReservation/<int:date>', views.delReservation, name='delReservation'),
    path('insertI/', views.insertIndivid, name='insertIndivid'),
    path('insertG/', views.insertGroup, name='insertGroup'),

]

gallery/models.py
from django.db import models
from PIL import Image
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.templatetags.static import static
from django.conf.urls.static import static
from django.conf import settings


class Photo(models.Model) :
    title = models.CharField(max_length=255)
    sub_title = models.CharField(max_length=255)
    img_num = models.IntegerField(null=False, default=0)
    photo_width = models.IntegerField(blank=True, null=True)
    photo_height = models.IntegerField(blank=True, null=True)
    photo = models.ImageField(upload_to='images/')

#이미지 사이즈 조절, 워터마크 넣는 기능
# sender(UploadPhoto)
@receiver(post_save, sender=Photo)
def overlay_watermark(instance, sender, **kwargs):
    photo = Image.open(instance.photo)
    width = instance.photo_width
    height = instance.photo_height
    print(width, height)
    watermark = Image.open("gallery/static/img/watermark.png")
    watermark = watermark.resize((150, 50), Image.ANTIALIAS)

    photo = photo.resize((width, height), Image.ANTIALIAS)
    photo.paste(watermark, (width-150, height-50), watermark)
    photo.save(instance.photo.path)

gallery/views.py
from django.shortcuts import render
from gallery.models import Photo
from django.contrib.auth import get_user_model


def gallery(request):
    return render(request, 'gallery/gallery.html')

def photographer(request):
    return render(request, 'gallery/photographer.html')

def project(request):
    return render(request, 'gallery/project.html')

def profile(request):
    return render(request, 'gallery/gallery_photographer_profile.html')





def Entrance(request):
    photos = Photo.objects.filter(title="location", sub_title="entrance")
    return render(request, 'gallery/gallery_location_Entrance.html', {'photos': photos})

def BackSide(request):
    photos = Photo.objects.filter(title="location", sub_title="backside")
    return render(request, 'gallery/gallery_location_BackSide.html', {'photos': photos})

def Garden(request):
    photos = Photo.objects.filter(title="location", sub_title="garden")
    return render(request, 'gallery/gallery_location_Garden.html', {'photos': photos})

def Indoor(request):
    photos = Photo.objects.filter(title="location", sub_title="indoor")
    return render(request, 'gallery/gallery_location_Indoor.html', {'photos': photos})

def Roof(request):
    photos = Photo.objects.filter(title="location", sub_title="root")
    return render(request, 'gallery/gallery_location_Roof.html', {'photos': photos})





def bada(request):
    photos = Photo.objects.filter(title="photographer", sub_title="김바다")
    return render(request, 'gallery/gallery_photographer_1.html', {'photos': photos})

def jeongmi(request):
    photos = Photo.objects.filter(title="photographer", sub_title="김정미")
    return render(request, 'gallery/gallery_photographer_2.html', {'photos': photos})

def seeun(request):
    photos = Photo.objects.filter(title="photographer", sub_title="안세은")
    return render(request, 'gallery/gallery_photographer_3.html', {'photos': photos})

def dayeon(request):
    photos = Photo.objects.filter(title="photographer", sub_title="양다연")
    return render(request, 'gallery/gallery_photographer_4.html', {'photos': photos})

def yeyoung(request):
    photos = Photo.objects.filter(title="photographer", sub_title="유예영")
    return render(request, 'gallery/gallery_photographer_5.html', {'photos': photos})

def seoyeon(request):
    photos = Photo.objects.filter(title="photographer", sub_title="이서연")
    return render(request, 'gallery/gallery_photographer_6.html', {'photos': photos})

def yeseo(request):
    photos = Photo.objects.filter(title="photographer", sub_title="예서")
    return render(request, 'gallery/gallery_photographer_7.html', {'photos': photos})

def minseo(request):
    photos = Photo.objects.filter(title="photographer", sub_title="민서")
    return render(request, 'gallery/gallery_photographer_8.html', {'photos': photos})

def sael(request):
    photos = Photo.objects.filter(title="photographer", sub_title="하사엘")
    return render(request, 'gallery/gallery_photographer_9.html', {'photos': photos})

def narae(request):
    photos = Photo.objects.filter(title="photographer", sub_title="한나래")
    return render(request, 'gallery/gallery_photographer_10.html', {'photos': photos})

def haewon(request):
    photos = Photo.objects.filter(title="photographer", sub_title="전해원")
    return render(request, 'gallery/gallery_photographer_11.html', {'photos': photos})

def seoyoung(request):
    photos = Photo.objects.filter(title="photographer", sub_title="장서영")
    return render(request, 'gallery/gallery_photographer_12.html', {'photos': photos})

def jinmin(request):
    photos = Photo.objects.filter(title="photographer", sub_title="성진민")
    return render(request, 'gallery/gallery_photographer_13.html', {'photos': photos})

def jinhee(request):
    photos = Photo.objects.filter(title="photographer", sub_title="주진희")
    return render(request, 'gallery/gallery_photographer_14.html', {'photos': photos})




def project(request):
    return render(request, 'gallery/gallery_project_slider.html')

def project1(request):
    photos = Photo.objects.filter(title="project", sub_title="project_1")
    return render(request, 'gallery/gallery_project_1.html', {'photos':photos})

def project2(request):
    photos = Photo.objects.filter(title="project", sub_title="project_2")
    return render(request, 'gallery/gallery_project_2.html', {'photos':photos})

def project3(request):
    photos = Photo.objects.filter(title="project", sub_title="project_3")
    return render(request, 'gallery/gallery_project_3.html', {'photos': photos})

def project4(request):
    photos = Photo.objects.filter(title="project", sub_title="project_4")
    return render(request, 'gallery/gallery_project_4.html', {'photos': photos})

def project5(request):
    photos = Photo.objects.filter(title="project", sub_title="project_5")
    return render(request, 'gallery/gallery_project_5.html', {'photos': photos})

def project6(request):
    photos = Photo.objects.filter(title="project", sub_title="project_6")
    return render(request, 'gallery/gallery_project_6.html', {'photos': photos})

def project7(request):
    photos = Photo.objects.filter(title="project", sub_title="project_7")
    return render(request, 'gallery/gallery_project_7.html', {'photos': photos})

def project8(request):
    photos = Photo.objects.filter(title="project", sub_title="project_8")
    return render(request, 'gallery/gallery_project_8.html', {'photos': photos})

def project9(request):
    photos = Photo.objects.filter(title="project", sub_title="project_9")
    return render(request, 'gallery/gallery_project_9.html', {'photos': photos})

gallery/templates/gallery/gallery_location_BackSide.html
<!--학교 뒷편-->

<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <title>Mirim in Photo | 갤러리</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/gallery_location.css' %}" type="text/css">
    <gallery></gallery>
</head>
{% load socialaccount %}
{% providers_media_js %}
<body>
    <div class="upper-nav">
        <a href="{% url 'mirim:index' %}">
            <img class="logo" src="{% static 'img/logo.svg' %}" />
        </a>
        <div class="inner-nav">
            {% if user.is_authenticated %}
            <a class="popper" data-popbox="pop">
                <a href="{% url 'reservation:list' %}"><div class="inner-nav-btn">RESERVATION</div></a>
            </a>
            {% else %}
            <a class="popper" data-popbox="pop">
                <div class="inner-nav-btn">RESERVATION</div>
            </a>
            {% endif %}
             <a href="{% url 'gallery:entrance' %}">
                <div class="inner-nav-btn">GALLERY</div>
            </a>
        </div>
    </div>
    <nav>
        <a href="{% url 'gallery:backside' %}">
            <div class="nav-loc">위치</div>
        </a>
        <a href="{% url 'gallery:project' %}">
            <div class="nav-pj">프로젝트</div>
        </a>
        <a href="{% url 'gallery:profile' %}">
            <div class="nav-pr">작가</div>
        </a>
    </nav>
    <main style="border:none;">
        <div class="place_container">
            <image src ="{% static 'img/schoolmap.jpg' %}" class = "mapimg" />
            <a href="{% url 'gallery:indoor' %}"><image src="{% static 'img/pin.png' %}" class = "pin1" /></a>
            <a href="{% url 'gallery:roof' %}"><image src="{% static 'img/pin.png' %}" class = "pin2" /></a>
            <a href="{% url 'gallery:entrance' %}"><image src="{% static 'img/pin.png' %}" class = "pin3" /></a>
            <a href="{% url 'gallery:garden' %}"><image src="{% static 'img/pin.png' %}" class = "pin4" /></a>
            <a href="{% url 'gallery:backside' %}"><image src="{% static 'img/pin.png' %}" class = "pin5" /></a>
        </div>
        <!-- 40부터 시작 -->
        <div class="place_info">학교 뒷편</div>
            {% for p in photos %}
            <div class="pj-{{p.img_num}}"><image src = "{{p.photo.url}}"/></div>
            {% endfor %}
    </main>
    <div id="pop" class="popbox">
        <div class="login-title">LOGIN</div>
        <div class="login-content">로그인 후 MIRIM IN PHOTO<br>
            프로젝트에 참여해보세요!</div>
        <div class="check-wrap">
            <input type="checkbox" name="remember-check" id="remember-check" />
            <label for="remember-check">로그인 상태 유지</label>
        </div>
        <a href="{% provider_login_url 'google' %}"><div class="login-btn">구글 아이디로 로그인</div></a>
    </div>

    <div class="footer5"></div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
    <script src="{% static 'js/nav.js' %}"></script>
</body>
</html>
{% load static %}

gallery/templates/gallery/gallery_location_Indoor.html
<!--교내-->

<!DOCTYPE html>
{% load static %}
<html lang="ko">

<head>
    <title>Mirim in Photo | 갤러리</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/gallery_location.css' %}" type="text/css">
</head>
{% load socialaccount %}
{% providers_media_js %}
<body>
    <div class="upper-nav">
        <a href="{% url 'mirim:index' %}">
            <img class="logo" src="{% static 'img/logo.svg' %}" />
        </a>
        <div class="inner-nav">
            {% if user.is_authenticated %}
            <a class="popper" data-popbox="pop">
                <a href="{% url 'reservation:list' %}"><div class="inner-nav-btn">RESERVATION</div></a>
            </a>
            {% else %}
            <a class="popper" data-popbox="pop">
                <div class="inner-nav-btn">RESERVATION</div>
            </a>
            {% endif %}
             <a href="{% url 'gallery:entrance' %}">
                <div class="inner-nav-btn">GALLERY</div>
            </a>
        </div>
    </div>
    <nav>
        <a href="{% url 'gallery:backside' %}">
            <div class="nav-loc">위치</div>
        </a>
        <a href="{% url 'gallery:project' %}">
            <div class="nav-pj">프로젝트</div>
        </a>
        <a href="{% url 'gallery:profile' %}">
            <div class="nav-pr">작가</div>
        </a>
    </nav>
    <main style="border:none;">
        <div class="place_container">
            <image src ="{% static 'img/schoolmap.jpg' %}" class = "mapimg" />
            <a href="{% url 'gallery:indoor' %}"><image src="{% static 'img/pin.png' %}" class = "pin1" /></a>
            <a href="{% url 'gallery:roof' %}"><image src="{% static 'img/pin.png' %}" class = "pin2" /></a>
            <a href="{% url 'gallery:entrance' %}"><image src="{% static 'img/pin.png' %}" class = "pin3" /></a>
            <a href="{% url 'gallery:garden' %}"><image src="{% static 'img/pin.png' %}" class = "pin4" /></a>
            <a href="{% url 'gallery:backside' %}"><image src="{% static 'img/pin.png' %}" class = "pin5" /></a>
        </div>
        <div class="place_info">교내</div>
        {% for p in photos %}
        <div class="pl-{{p.img_num}}"><image src = "{{p.photo.url}}"/></div>
        {% endfor %}
    </main>

    <div id="pop" class="popbox">
        <div class="login-title">LOGIN</div>
        <div class="login-content">로그인 후 MIRIM IN PHOTO<br>
            프로젝트에 참여해보세요!</div>
        <div class="check-wrap">
            <input type="checkbox" name="remember-check" id="remember-check" />
            <label for="remember-check">로그인 상태 유지</label>
        </div>
        <a href="{% provider_login_url 'google' %}"><div class="login-btn">구글 아이디로 로그인</div></a>
    </div>


    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
    <script src="{% static 'js/nav.js' %}"></script>

</body>
</html>
{% load static %}

gallery/templates/gallery/gallery_photographer_1.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <title>Mirim in Photo | 갤러리</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/gallery_photographer.css' %}" type="text/css">
</head>
{% load socialaccount %}
{% providers_media_js %}
<body style="height: 4800px">
    <div class="upper-nav">
       <a href="{% url 'mirim:index' %}">
            <img class="logo" src="{% static 'img/logo.svg' %}" />
        </a>
        <div class="inner-nav">
            {% if user.is_authenticated %}
            <a class="popper" data-popbox="pop">
                <a href="{% url 'reservation:list' %}"><div class="inner-nav-btn">RESERVATION</div></a>
            </a>
            {% else %}
            <a class="popper" data-popbox="pop">
                <div class="inner-nav-btn">RESERVATION</div>
            </a>
            {% endif %}
             <a href="{% url 'gallery:entrance' %}">
                <div class="inner-nav-btn">GALLERY</div>
            </a>
        </div>
    </div>
    <nav>
        <a href="{% url 'gallery:backside' %}">
            <div class="nav-loc">위치</div>
        </a>
        <a href="{% url 'gallery:project' %}">
            <div class="nav-pj">프로젝트</div>
        </a>
        <a href="{% url 'gallery:profile' %}">
            <div class="nav-pr">작가</div>
        </a>
    </nav>
    <main style="border:none;">
        <div class="pr-area">
            <div class="pr-name">김바다 Kim Bada</div>
            <div class="pr-intro">"뭐든 잘 될 거야"</div>
        </div>
        <div class="photo-area">
            {% for p in photos %}
            <div class="p-{{p.img_num}}"><image src = "{{p.photo.url}}"/></div>
            {% endfor %}
        </div>
    </main>
    <div id="pop" class="popbox">
        <div class="login-title">LOGIN</div>
        <div class="login-content">로그인 후 MIRIM IN PHOTO<br>
            프로젝트에 참여해보세요!</div>
        <div class="check-wrap">
            <input type="checkbox" name="remember-check" id="remember-check" />
            <label for="remember-check">로그인 상태 유지</label>
        </div>
        <a href="{% provider_login_url 'google' %}"><div class="login-btn">구글 아이디로 로그인</div></a>
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
    <script src="{% static 'js/nav.js' %}"></script>
</body>

</html>

gallery/templates/gallery/gallery_photographer_10.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <title>Mirim in Photo | 갤러리</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/gallery_photographer.css' %}" type="text/css">
</head>
{% load socialaccount %}
{% providers_media_js %}
<body style="height: 4600px">
    <div class="upper-nav">
        <a href="{% url 'mirim:index' %}">
            <img class="logo" src="{% static 'img/logo.svg' %}" />
        </a>
        <div class="inner-nav">
            {% if user.is_authenticated %}
            <a class="popper" data-popbox="pop">
                <a href="{% url 'reservation:list' %}"><div class="inner-nav-btn">RESERVATION</div></a>
            </a>
            {% else %}
            <a class="popper" data-popbox="pop">
                <div class="inner-nav-btn">RESERVATION</div>
            </a>
            {% endif %}
             <a href="{% url 'gallery:entrance' %}">
                <div class="inner-nav-btn">GALLERY</div>
            </a>
        </div>
    </div>
    <nav>
        <a href="{% url 'gallery:backside' %}">
            <div class="nav-loc">위치</div>
        </a>
        <a href="{% url 'gallery:project' %}">
            <div class="nav-pj">프로젝트</div>
        </a>
        <a href="{% url 'gallery:profile' %}">
            <div class="nav-pr">작가</div>
        </a>
    </nav>
    <main style="border:none;">
        <div class="pr-area">
            <div class="pr-name">한나래 Han NaRae</div>
            <div class="pr-intro">"뭐든 잘 될 거야"</div>
        </div>
        <div class="photo-area">
            {% for p in photos %}
            <div class="p-{{p.img_num}}"><image src = "{{p.photo.url}}"/></div>
            {% endfor %}
        </div>
    </main>
    <div id="pop" class="popbox">
        <div class="login-title">LOGIN</div>
        <div class="login-content">로그인 후 MIRIM IN PHOTO<br>
            프로젝트에 참여해보세요!</div>
        <div class="check-wrap">
            <input type="checkbox" name="remember-check" id="remember-check" />
            <label for="remember-check">로그인 상태 유지</label>
        </div>
        <a href="{% provider_login_url 'google' %}"><div class="login-btn">구글 아이디로 로그인</div></a>
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
    <script src="{% static 'js/nav.js' %}"></script>
</body>

</html>

gallery/templates/gallery/gallery_photographer_12.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <title>Mirim in Photo | 갤러리</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/gallery_photographer.css' %}" type="text/css">
</head>
{% load socialaccount %}
{% providers_media_js %}
<body style="height: 5620px">
    <div class="upper-nav">
        <a href="{% url 'mirim:index' %}">
            <img class="logo" src="{% static 'img/logo.svg' %}" />
        </a>
        <div class="inner-nav">
            {% if user.is_authenticated %}
            <a class="popper" data-popbox="pop">
                <a href="{% url 'reservation:list' %}"><div class="inner-nav-btn">RESERVATION</div></a>
            </a>
            {% else %}
            <a class="popper" data-popbox="pop">
                <div class="inner-nav-btn">RESERVATION</div>
            </a>
            {% endif %}
             <a href="{% url 'gallery:entrance' %}">
                <div class="inner-nav-btn">GALLERY</div>
            </a>
        </div>
    </div>
    <nav>
        <a href="{% url 'gallery:backside' %}">
            <div class="nav-loc">위치</div>
        </a>
        <a href="{% url 'gallery:project' %}">
            <div class="nav-pj">프로젝트</div>
        </a>
        <a href="{% url 'gallery:profile' %}">
            <div class="nav-pr">작가</div>
        </a>
    </nav>
    <main style="border:none;">
        <div class="pr-area">
            <div class="pr-name">장서영 Jang SeoYoung</div>
            <div class="pr-intro">"뭐든 잘 될 거야"</div>
        </div>
        <div class="photo-area">
            {% for p in photos %}
            <div class="p-{{p.img_num}}"><image src = "{{p.photo.url}}"/></div>
            {% endfor %}
        </div>
    </main>
    <div id="pop" class="popbox">
        <div class="login-title">LOGIN</div>
        <div class="login-content">로그인 후 MIRIM IN PHOTO<br>
            프로젝트에 참여해보세요!</div>
        <div class="check-wrap">
            <input type="checkbox" name="remember-check" id="remember-check" />
            <label for="remember-check">로그인 상태 유지</label>
        </div>
        <a href="{% provider_login_url 'google' %}"><div class="login-btn">구글 아이디로 로그인</div></a>
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
    <script src="{% static 'js/nav.js' %}"></script>
</body>

</html>

gallery/templates/gallery/gallery_photographer_profile.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    <title>Mirim in Photo | 갤러리</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/gallery_photographer.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/gallery_photographer_profile.css' %}" type="text/css">
</head>

<body style="height: 2300px">
    <div class="upper-nav">
        <a href="{% url 'mirim:index' %}">
            <img class="logo" src="{% static 'img/logo.svg' %}" />
        </a>
        <div class="inner-nav">
            {% if user.is_authenticated %}
            <a class="popper" data-popbox="pop">
                <a href="{% url 'reservation:list' %}"><div class="inner-nav-btn">RESERVATION</div></a>
            </a>
            {% else %}
            <a class="popper" data-popbox="pop">
                <div class="inner-nav-btn">RESERVATION</div>
            </a>
            {% endif %}
             <a href="{% url 'gallery:entrance' %}">
                <div class="inner-nav-btn">GALLERY</div>
            </a>
        </div>
    </div>
    <nav>
        <a href="{% url 'gallery:entrance' %}">
            <div class="nav-loc">위치</div>
        </a>
        <a href="{% url 'gallery:project' %}">
            <div class="nav-pj">프로젝트</div>
        </a>
        <a href="{% url 'gallery:profile' %}">
            <div class="nav-pr">작가</div>
        </a>
    </nav>
    <main>
        <div class="profile-1"><a href="{% url 'gallery:haewon' %}"><img src="{% static 'img/profile_1.png' %}"></a></div>
        <div class="profile-2"><a href="{% url 'gallery:jinmin' %}"><img src="{% static 'img/profile_2.png' %}"></a></div>
        <div class="profile-3"><a href="{% url 'gallery:seoyeon' %}"><img src="{% static 'img/profile_3.png' %}"></a></div>
        <div class="profile-4"><a href="{% url 'gallery:yeseo' %}"><img src="{% static 'img/profile_4.png' %}"></a></div>
        <div class="profile-5"><a href="{% url 'gallery:narae' %}"><img src="{% static 'img/profile_5.png' %}"></a></div>
        <div class="profile-6"><a href="{% url 'gallery:minseo' %}"><img src="{% static 'img/profile_6.png' %}"></a></div>
        <div class="profile-7"><a href="{% url 'gallery:jeongmi' %}"><img src="{% static 'img/profile_7.png' %}"></a></div>
        <div class="profile-8"><a href="{% url 'gallery:yeyoung' %}"><img src="{% static 'img/profile_8.png' %}"></a></div>
        <div class="profile-9"><a href="{% url 'gallery:seeun' %}"><img src="{% static 'img/profile_9.png' %}"></a></div>
        <div class="profile-10"><a href="{% url 'gallery:sael' %}"><img src="{% static 'img/profile_10.png' %}"></a></div>
        <div class="profile-11"><a href="{% url 'gallery:bada' %}"><img src="{% static 'img/profile_11.png' %}"></a></div>
        <div class="profile-12"><a href="{% url 'gallery:jinhee' %}"><img src="{% static 'img/profile_12.png' %}"></a></div>
        <div class="profile-13"><a href="{% url 'gallery:seoyoung' %}"><img src="{% static 'img/profile_13.png' %}"></a></div>
        <div class="profile-14"><a href="{% url 'gallery:dayeon' %}"><img src="{% static 'img/profile_14.png' %}"></a></div>
    </main>
    <div id="pop" class="popbox">
        <div class="login-title">LOGIN</div>
        <div class="login-content">로그인 후 MIRIM IN PHOTO<br>
            프로젝트에 참여해보세요!</div>
        <div class="check-wrap">
            <input type="checkbox" name="remember-check" id="remember-check" />
            <label for="remember-check">로그인 상태 유지</label>
        </div>
        <div class="login-btn">구글 아이디로 로그인</div>
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js" type="text/javascript"></script>
    <script src="{% static 'js/nav.js' %}"></script>
</body>

</html>